[package]
name = "fermi-io"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[dependencies]
anyhow = "1.0"
hf-hub = "0.4"
tokenizers = "0.21"
serde_json = "1.0"
fermi-models = { path = "../fermi-models" }
